import{a as m,i as p,S as g}from"./assets/vendor-506f5d81.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const y="45375111-d1e8183fd09326f55157dfb1e",b="https://pixabay.com/api/";async function w(e,o=1,s=15){const a=`${b}?key=${y}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${s}`;try{const r=(await m.get(a)).data;if(r.totalHits===0)throw new Error("Sorry, there are no images matching your search query. Please, try again!");return r}catch(t){throw t}}function L(e,o){const s=e.map(a=>v(a)).join("");o.insertAdjacentHTML("beforeend",s)}function v({webformatURL:e,largeImageURL:o,tags:s,likes:a,views:t,comments:r,downloads:i}){return`
    <a href="${o}" class="gallery__item">
      <img src="${e}" alt="${s}" loading="lazy" class="gallery__image"/>
      <div class="gallery__info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${t}</p>
        <p><b>Comments:</b> ${r}</p>
        <p><b>Downloads:</b> ${i}</p>
      </div>
    </a>
  `}function S(e){e.innerHTML=""}function c(e,o="info"){p[o]({title:o.charAt(0).toUpperCase()+o.slice(1),message:e,position:"topRight",backgroundColor:"#ef4040",titleColor:"#fafafb",messageColor:"#fafafb",borderBottom:"2px solid #ffbebe",borderRadius:"4px",padding:"20px",width:"432px",height:"88px",fontSize:"16px",fontWeight:"400",lineHeight:"1.5",letterSpacing:"0.03em",messageMaxWidth:"100%",messageOverflow:"hidden",wordBreak:"break-word",wordWrap:"break-word"})}function x(e){e.classList.add("visible")}function _(e){e.classList.remove("visible")}const $=document.querySelector("#search-form"),f=document.querySelector(".gallery"),u=document.querySelector(".loader"),n=document.querySelector(".load-more");let d="",l=1,q=new g(".gallery a");$.addEventListener("submit",async e=>{if(e.preventDefault(),d=e.currentTarget.elements.searchQuery.value.trim(),d===""){c("Please enter a search query","warning");return}S(f),l=1,await h()});async function h(){try{x(u);const e=await w(d,l);if(e.hits.length===0){c("Sorry, there are no images matching your search query. Please, try again!","error"),n.classList.add("hidden");return}L(e.hits,f),q.refresh(),l*15>=e.totalHits?(n.classList.add("hidden"),c("We're sorry, but you've reached the end of search results.","info")):n.classList.remove("hidden"),E()}catch(e){c(e.message,"error")}finally{_(u)}}function C(){n.addEventListener("click",async()=>{l+=1,await h()})}function E(){const e=document.querySelector(".gallery__item");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}n.classList.add("hidden");C();
//# sourceMappingURL=commonHelpers.js.map
